data:
  corpus_1:
    path_src: onmt_data/train.bpe.ach
    path_tgt: onmt_data/train.bpe.en
  valid:
    path_src: onmt_data/dev.bpe.ach
    path_tgt: onmt_data/dev.bpe.en
overwrite: false
save_data: onmt_data/data
share_vocab: false
src_vocab: onmt_data/data.vocab.ach
src_vocab_size: 7000
src_words_min_frequency: 2
tgt_vocab: onmt_data/data.vocab.en
tgt_vocab_size: 7000
tgt_words_min_frequency: 2
transforms:
- filtertoolong
